ALTER TABLE passenger MODIFY COLUMN name VARCHAR(255) NOT NULL;

ALTER TABLE passenger ADD COLUMN email VARCHAR(255) NOT NULL;
ALTER TABLE passenger ADD COLUMN password VARCHAR(255) NOT NULL;

ALTER TABLE passenger ADD CONSTRAINT UQ_PASSENGER_EMAIL UNIQUE (email)